--- # AWS IAM MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars:
    access_key: AKIAJWSMXFXLOIREJAUQ
    secret_key: bsMf8I1pP4B6MENZVeqE0uyMGEa3A//WHmS8pNtf
    ami_id: ami-a4dc46db
    region: us-east-1

################# IAM GROUP CREATION ###################
  tasks:
  - name: Creating  IAM Group
    iam:
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      region: "{{region}}"
      iam_type: group 
      name: administrators  
      state: present
########################--policy creation--##################################
  - name: creating admin access
    iam_policy:
      iam_type: group    
      iam_name: administrators  
      policy_name: Admin
      state: present
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      region: "{{region}}"
      validate_certs: yes
      policy_document: admin.json
##################--IAM USER CREATION--###################################      
  - name: Create  IAM User and add users into group(administrators)
    iam:
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      region: "{{region}}"
      iam_type: user
      name: testuser
      state: present
      groups: administrators
      password: "test"
      access_key_state: create
      access_key_ids: create
    register: iam
  - name: Show the JSON Results
    debug: var=iam
