---
- hosts: localhost
  connection: localhost
  remote_user: root
  gather_facts: no
  vars:
    access_key: AKIAJWSMXFXLOIREJAUQ
    secret_key:  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
    inventory_file: int-dev

  tasks:
    - name: creating security group for jenkins server
      ec2_group:
        name: jenkins-SG
        description: this is security group for jenkins
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    
    - name: create a jenkins key
      ec2_key: 
        name: jenkins_key
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        region: us-east-1
      register: jenkins_key

    - debug: 
        msg: "{{jenkins_key.key.private_key}}"
      ignore_errors: true


    - name: save private key
      copy:
        content: "{{jenkins_key.key.private_key}}\n"
        dest: "./jenkins_key.pem"
        mode: 0600
      when: jenkins_key.changed
      ignore_errors: true


    - name: create EC2 instance
      ec2:
        key_name: jenkins_key
        instance_type: t2.micro
        aws_access_key: "{{access_key}}" 
        aws_secret_key: "{{secret_key}}"
        region: us-east-1
        image: ami-43a15f3e
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
             Name: jenkins
             owner: admin
        monitoring: no 
        vpc_subnet_id: subnet-2a396077
        assign_public_ip: yes
        group: jenkins-SG
      register: ec2_out
      ignore_errors: true

    - debug:
        msg:  "{{ec2_out.instances[0].public_ip}}"
    - name: name for ssh to comeup
      wait_for: host={{ec2_out.instances[0].public_ip}} port=22 delay=60 timeout=500 state=started

    - name: create inventory file
      shell:  echo "jenkins ansible_ssh_host="{{ec2_out.instances[0].public_ip}}""  > int-dev


    - name: appending the file
      shell:  cat invent-dev >> int-dev

    - name: add instance ip to ansible grp
      add_host:
        hostname: jenkins
        ansible_ssh_host: "{{ec2_out.instances[0].public_ip}}"
        ansible_ssh_user: ubuntu
        groupname: vprohosts


    - name: wait for port 22 to be ready
      wait_for: host={{ec2_out.instances[0].public_ip}}  port=22  delay=60 timeout=320 state=started



####################### INSTALLING JENKINS ##########################
        
- hosts: jenkins
  become: yes
  remote_user: root
  gather_facts: false
  tasks:
    - name: install packages
      apt:
        update_cache: yes
        name: "{{item}}"
        state: present
      with_items:
        - wget
        - git
        - openjdk-8-jdk
        - maven
        - python
      ignore_errors: true


    - name: import jenkins key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present

    - name: Debian package repository of Jenkins and add key
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        filename: jenkins.list
        state: present


    - name: install jenkins 
      apt:
        name: jenkins
        state: present
       
    - name: disable the firewall
      ufw:
        rule: deny
        state: disabled

    - name: installing software package
      apt:
        name: software-properties-common
        state: present

    - name: add repository for ansible
      apt_repository: 
        repo: 'ppa:ansible/ansible'


    - name: install ansible
      apt:
        name: ansible 
        state: present


